### ISSUE TITLE
Obtain relevant basepath / chroot info from FSAL

### ISSUE THREAD

**Issue by foxbunny** [Outernet-Project/lftp#4]
To avoid duplication of configuration, please obtain relevant configuration parameters from FSAL directly instead of the configuration file.

**Comment by goodbadwolf** [comment]
I want to avoid dependency on FSAL if possible. This can be solved by having a common config snippet which has all the path related settings, which is then included in by FSAL's & LFTP's config files.
The change required to the application code will be minimal, just the config keys and this won't introduce any pesky service startup ordering issues.

**Comment by goodbadwolf** [comment]
Closed till further notice.
